# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
     env
  displayName: 'Look at ENV vars'

- task: VaultReadKV@2
  inputs:
    strUrl: 'https://vault.marc-leblanc.team.arctiq.ca:8200'
    ignoreCertificateChecks: false
    strAuthType: 'approle'
    strAuthPath: 'approle'
    strRoleID: '7f99d535-7b94-6cf1-5a05-82b3e8005714'
    strSecretID: '8faf471e-d2a0-8b64-cd79-a730e4a0e1eb'
    strKVEnginePath: '/kv-v2/'
    kvVersion: 'v2'
    strSecretPath: '/secret/hello/'
    strPrefixType: 'custom'
    replaceCR: false

